root: 
  ./docs/
​structure:
  readme: README.md
  summary: SUMMARY.md​
redirects:
  latest/quickstart/get-api-key: latest/quickstart.md
  quickstart/get-api-key: quickstart.md
  quickstart/installation: quickstart.md
  quickstart/authentication: quickstart.md
  quickstart/connect-a-device: quickstart.md
  quickstart/your-first-device-api-call: quickstart.md
  quickstart/going-live: quickstart.md
  going-live: go-live.md
  core-concepts/workspaces/api-keys: core-concepts/authentication/api-keys.md
  core-concepts/workspaces/personal-access-tokens: core-concepts/authentication/personal-access-tokens.md
  core-concepts/workspaces/client-session-tokens: core-concepts/authentication/client-session-tokens/README.md
  core-concepts/workspaces/client-session-tokens/implementing-client-sessions-for-device-management-in-the-backend: core-concepts/authentication/client-session-tokens/implementing-client-sessions-for-device-management-in-the-backend.md
  
