---
root: ./docs/
​structure:
  readme: README.md
  summary: SUMMARY.md​
redirects:
  latest/quickstart/get-api-key: latest/quickstart.md
  quickstart/get-api-key: quickstart.md
  quickstart/installation: quickstart.md
  quickstart/authentication: quickstart.md
  quickstart/connect-a-device: quickstart.md
  quickstart/your-first-device-api-call: quickstart.md
  quickstart/going-live: quickstart.md
  going-live: go-live.md
  core-concepts/workspaces/api-keys: core-concepts/authentication/api-keys.md
  core-concepts/workspaces/personal-access-tokens: core-concepts/authentication/personal-access-tokens.md
  core-concepts/workspaces/client-session-tokens: core-concepts/authentication/client-session-tokens/README.md
  core-concepts/workspaces/client-session-tokens/implementing-client-sessions-for-device-management-in-the-backend: core-concepts/authentication/client-session-tokens/implementing-client-sessions-for-device-management-in-the-backend.md
  products/access-systems/user-management: capability-guides/access-systems/user-management/README.md
  capability-guides/access-systems/managing-credentials: capability-guides/access-systems/managing-credentials/README.md
  capability-guides/access-systems/assigning-credentials-to-users: capability-guides/access-systems/managing-credentials/assigning-credentials-to-users.md
  products/access-systems/suspending-and-unsuspending-users: capability-guides/access-systems/user-management/suspending-and-unsuspending-users.md
  products/seam-bridge-in-development: capability-guides/seam-bridge.md
  core-concepts/connect-webviews: core-concepts/connect-webviews/README.md
  device-guides/4suites-locks: device-and-system-integration-guides/4suites-locks/README.md
  device-guides/assa-abloy-visionline-access-control-system-in-development: device-and-system-integration-guides/assa-abloy-visionline-access-control-system/README.md
  device-guides/assa-abloy-visionline-access-control-system-in-development/credential-types: device-and-system-integration-guides/assa-abloy-visionline-access-control-system/credential-types.md
  device-and-system-integration-guides/assa-abloy-visionline-access-control-system-in-development/visionline-credential-metadata: device-and-system-integration-guides/assa-abloy-visionline-access-control-system/visionline-credential-metadata.md
  device-guides/assa-abloy-visionline-access-control-system-in-development/common-use-cases: device-and-system-integration-guides/assa-abloy-visionline-access-control-system/common-use-cases.md
  device-and-system-integration-guides/assa-abloy-visionline-access-control-system-in-development/special-requirements-for-android-mobile-access-sdk-development: device-and-system-integration-guides/assa-abloy-visionline-access-control-system/special-requirements-for-android-mobile-access-sdk-development.md
  device-and-system-integration-guides/assa-abloy-visionline-access-control-system-in-development/special-requirements-for-ios-mobile-access-sdk-development: device-and-system-integration-guides/assa-abloy-visionline-access-control-system/special-requirements-for-ios-mobile-access-sdk-development.md
  capability-guides/access-systems/understanding-acs-differences: capability-guides/access-systems/understanding-access-control-system-differences.md
  device-guides/get-started-with-schlage-locks: device-and-system-integration-guides/schlage-locks/get-started-with-schlage-locks.md
